class NavyFoxError(Exception): ...
class DocumentClosedError(NavyFoxError): ...
class StaleProxyError(NavyFoxError): ...
class OwnershipError(NavyFoxError): ...
class NativeRuntimeError(RuntimeError, NavyFoxError): ...
class NonexistentCachedPageCount(RuntimeError, NavyFoxError): ...
