from collections.abc import Iterable, Iterator
from typing import Self, TypeVar, overload

from fastdocx._native.handle import Handle
from fastdocx._proxy.base import ProxyBase
from fastdocx.document import Document

_VT = TypeVar("_VT", bound=ProxyBase)

ElemTypesArg = type[_VT] | tuple[type[_VT], ...]

class CollectionMixin[T: ProxyBase]:
    @property
    def first(self) -> T | None: ...
    @property
    def last(self) -> T | None: ...
    def append(self, element: T) -> None: ...
    def extend(self, elements: Iterable[T]) -> None: ...
    def insert(self, index: int, element: T) -> None: ...
    def remove(self, element: T) -> None: ...
    def pop(self, index: int = ...) -> T: ...
    def clear(self) -> None: ...
    def index(self, element: T) -> int: ...
    def _append_one(self, element: T) -> T: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    def __reversed__(self) -> Iterator[T]: ...
    def __contains__(self, element: object) -> bool: ...
    def __iadd__(self, elements: Iterable[T]) -> Self: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> DocumentView[T]: ...

class DocumentView[T: ProxyBase](CollectionMixin[T]):
    def __init__(
        self,
        parent_handle: int,
        document: Document,
        lib: Handle,
        elem_types: ElemTypesArg[T],
        collection_name: str,
    ) -> None: ...
    @staticmethod
    def empty(elem_types: ElemTypesArg[_VT], collection_name: str) -> DocumentView[_VT]: ...
    def __bool__(self) -> bool: ...
    def __or__[U: ProxyBase](self, other: DocumentView[U]) -> DocumentView[T | U]: ...
    def __repr__(self) -> str: ...
