from collections.abc import Iterable, Sequence
from typing import Self, TypeVar, overload

from fastdocx._proxy.base import ProxyBase
from fastdocx.collection import CollectionMixin, DocumentView
from fastdocx.paragraph import Paragraph
from fastdocx.section import Section
from fastdocx.styles import Style, StyleCollection
from fastdocx.table import Table

DocumentElementT = TypeVar("DocumentElementT", bound=ProxyBase)

class Document(CollectionMixin[Paragraph | Table]):
    def __init__(self) -> None: ...
    @classmethod
    def open(cls, path: str) -> Document: ...
    @classmethod
    def edit(cls, path: str) -> Document: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def path(self) -> str | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *_: object) -> None: ...
    def save(self, path: str | None = ...) -> None: ...
    @property
    def styles(self) -> StyleCollection: ...
    @property
    def default_style(self) -> Style | None: ...
    @property
    def author(self) -> str: ...
    @author.setter
    def author(self, value: str) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def subject(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def page_count(self) -> int: ...
    @property
    def paragraphs(self) -> DocumentView[Paragraph]: ...
    @property
    def tables(self) -> DocumentView[Table]: ...
    @property
    def sections(self) -> DocumentView[Section]: ...
    def group(self, types: Sequence[type[DocumentElementT]]) -> DocumentView[DocumentElementT]: ...
    def add_paragraph(self, text: str = ..., style: str = ...) -> Paragraph: ...
    def add_heading(self, text: str = ..., level: int = ...) -> Paragraph: ...
    def add_table(self, rows: int, cols: int, style: str = ...) -> Table: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, element: object) -> bool: ...
    def __iadd__(self, elements: Iterable[Paragraph | Table]) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    @overload
    def __getitem__(self, key: int) -> Paragraph | Table: ...
    @overload
    def __getitem__(self, key: slice) -> DocumentView[Paragraph | Table]: ...
    @overload
    def __getitem__(self, key: type[DocumentElementT]) -> DocumentView[DocumentElementT]: ...
