class FastDocxError(Exception): ...

class DocumentClosedError(FastDocxError): ...

class StaleProxyError(FastDocxError): ...

class OwnershipError(FastDocxError): ...

class NativeRuntimeError(RuntimeError, FastDocxError): ...

class NonexistentCachedPageCount(RuntimeError, FastDocxError): ...
