from typing import Iterator, Literal


class Style:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> Literal["paragraph", "character", "table", "numbering"]: ...
    @property
    def based_on(self) -> str | None: ...
    @property
    def next_style(self) -> str | None: ...
    @property
    def is_default(self) -> bool: ...
    def __repr__(self) -> str: ...


class StyleCollection:
    @property
    def default(self) -> Style | None: ...
    def __getitem__(self, name: str) -> Style: ...
    def __contains__(self, name: object) -> bool: ...
    def __iter__(self) -> Iterator[Style]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
