from collections.abc import Iterator
from typing import Any, Literal, overload

from fastdocx._collection import DocumentView as DocumentView
from fastdocx._proxy.base import ProxyBase as _ProxyBase
from fastdocx.paragraph import Paragraph

class Cell(_ProxyBase):
    text: str
    width: float
    vertical_alignment: Literal["top", "center", "bottom"]
    merge_up: str
    merge_left: str

    @property
    def paragraphs(self) -> DocumentView[Paragraph]: ...
    def merge(self, other: Cell) -> None: ...
    def _copy_data(self) -> dict[str, Any]: ...
    def copy(self) -> Cell: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Paragraph]: ...

class Row(_ProxyBase):
    height: float
    height_rule: Literal["auto", "exact", "atLeast"]
    is_header: str
    cant_split: str

    @property
    def cells(self) -> DocumentView[Cell]: ...
    def _copy_data(self) -> dict[str, Any]: ...
    def copy(self) -> Row: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Cell]: ...
    def __getitem__(self, index: int) -> Cell: ...

class Table(_ProxyBase):
    style: str
    alignment: Literal["left", "center", "right"] | None
    width: float
    indent: float
    cell_spacing: float

    def __init__(
        self,
        rows: int,
        cols: int,
        *,
        style: str = ...,
    ) -> None: ...
    @property
    def rows(self) -> DocumentView[Row]: ...
    @property
    def cells(self) -> DocumentView[Cell]: ...
    @property
    def data(self) -> list[list[str]]: ...
    def cell(self, row: int, col: int) -> Cell: ...
    def _copy_data(self) -> dict[str, Any]: ...
    def copy(self) -> Table: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Row]: ...
    def __contains__(self, row: object) -> bool: ...
    @overload
    def __getitem__(self, index: int) -> Row: ...
    @overload
    def __getitem__(self, index: tuple[int, int]) -> Cell: ...
