from __future__ import annotations

from collections.abc import Iterable, Iterator
from typing import TYPE_CHECKING, Self, overload

from docxmint._native.handle import Handle
from docxmint._proxy.base import ProxyBase

if TYPE_CHECKING:
    from docxmint.document import Document

type ElemTypesArg[T: ProxyBase] = type[T] | tuple[type[T], ...]

class CollectionMixin[T: ProxyBase]:
    @property
    def first(self) -> T | None: ...
    @property
    def last(self) -> T | None: ...
    def append(self, element: T) -> None: ...
    def extend(self, elements: Iterable[T]) -> None: ...
    def insert(self, index: int, element: T) -> None: ...
    def remove(self, element: T) -> None: ...
    def pop(self, index: int = ...) -> T: ...
    def clear(self) -> None: ...
    def index(self, element: T) -> int: ...
    def _append_one(self, element: T) -> T: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    def __reversed__(self) -> Iterator[T]: ...
    def __contains__(self, element: object) -> bool: ...
    def __iadd__(self, elements: Iterable[T]) -> Self: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> DocumentView[T]: ...

class DocumentView[T: ProxyBase](CollectionMixin[T]):
    def __init__(
        self,
        parent_handle: int,
        document: Document,
        lib: Handle,
        elem_types: ElemTypesArg[T],
        collection_name: str,
    ) -> None: ...
    @staticmethod
    def empty[VT: ProxyBase](
        elem_types: ElemTypesArg[VT], collection_name: str
    ) -> DocumentView[VT]: ...
    def __bool__(self) -> bool: ...
    def __or__[U: ProxyBase](self, other: DocumentView[U]) -> DocumentView[T | U]: ...
    def __repr__(self) -> str: ...
