class DocxMintError(Exception): ...
class DocumentClosedError(DocxMintError): ...
class StaleProxyError(DocxMintError): ...
class OwnershipError(DocxMintError): ...
class NativeRuntimeError(RuntimeError, DocxMintError): ...
class NonexistentCachedPageCount(RuntimeError, DocxMintError): ...
